- name: Converge
  hosts: all
  become: true
  vars:
    db_name: prism
    db_user: prism
    db_private_ip: "127.0.0.1"
    s3_bucket_name: "prism-backups-test"
    aws_region: "eu-west-3"
    backup_cron_hour: "2"
    backup_cron_minute: "0"
    backup_retention_days: 7
  roles:
    - role: backup
